import{a as L,S as w,i as l}from"./assets/vendor-CYg6pwNI.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const S="49266209-5c1ed6293a40b594db6a6f47f",v="https://pixabay.com/api/";async function p(t,e=1,i=15){try{return(await L.get(v,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:i}})).data}catch(s){throw console.error("Помилка отримання зображень:",s.message),s}}const f=document.querySelector(".gallery"),h=document.querySelector(".loader");let E=new w(".gallery a",{captionsData:"alt",captionDelay:250,animationSlide:!0});function q(t){return t.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
            </a>
            <div class="info">
                <p><b>Likes:</b> ${e.likes}</p>
                <p><b>Views:</b> ${e.views}</p>
                <p><b>Comments:</b> ${e.comments}</p>
                <p><b>Downloads:</b> ${e.downloads}</p>
            </div>
        </li>
    `).join("")}function m(t){const e=document.querySelector(".gallery");if(!t||t.length===0){l.warning({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}e.insertAdjacentHTML("beforeend",q(t)),E.refresh()}function R(){f.innerHTML=""}function P(){const{height:t}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const g=()=>{h.style.display="block"},b=()=>{h.style.display="none"},$=document.querySelector(".form"),O=document.querySelector(".form-input"),n=document.querySelector(".load-more");let c="",a=1,u=0;const y=15;$.addEventListener("submit",async t=>{if(t.preventDefault(),c=O.value.trim(),!c){l.error({title:"Error",message:"Enter a search query",position:"topRight"});return}R(),g(),n.style.display="none",a=1;try{const{hits:e,totalHits:i}=await p(c,a,y);u=i,m(e),e.length<u&&(n.style.display="block")}catch{l.error({title:"Error",message:"Failed to fetch images. Try again.",position:"topRight"})}finally{b()}});n.addEventListener("click",async()=>{a++,g(),n.style.display="none";try{const{hits:t}=await p(c,a,y);m(t),P(),a*y>=u?(n.style.display="none",l.info({title:"End",message:"We're sorry, but you've reached the end of search results",position:"topRight"})):n.style.display="block"}catch{l.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
